# Site settings
title: Ralph
email:
description:
repo_link: "https://github.com/allegro/ralph"
documentation_link: "https://ralph-ng.readthedocs.io/"
installation_link: "https://ralph-ng.readthedocs.io/en/stable/installation/installation/"
demo_link: "http://ralph-demo.allegro.tech/"
gitter_link: "https://gitter.im/allegro/ralph"
issues_link: "https://github.com/allegro/ralph/issues"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
